Section "Device"
	Identifier "Intel Graphics"
	Driver "modesetting"
	BusID "PCI:0:2:0"
	Option "TearFree" "true"
EndSection

Section "Device"
	Identifier "NVIDIA Graphics"
	Driver "nvidia"
	Option "TearFree" "true"
	BusID "PCI:1:0:0"
EndSection


Section "ServerFlags"
	Option "IgnoreABI" "true"
EndSection
