Section "InputClass"
	Identifier "keyboard"
	MatchIsKeyboard "on"
	Option "XKbLayout" "tr,us"
	Option "XKbOptions" "grp:win_space_toggle,compose:rctrl,caps:escape,terminate:ctrl_alt_bksp"
EndSection

